version: '2.4'

volumes:
  local_postgres_data: {}
  ldap_data_local: {}
  ldap_config_local: {}

services:
  backbone_server: &backbone_server
    build:
      context: .
      dockerfile: ./compose/local/backbone_server/Dockerfile
    image: local_backbone_server
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.backbone_server
      - ./.envs/.local/.postgres
      - ./.envs/.local/.ldap
    ports:
      - "8100:8080"
    command: /start

  import: &import
    build:
      context: .
      dockerfile: ./compose/local/import/Dockerfile
    image: local_import
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.backbone_server
      - ./.envs/.local/.postgres
    command: /start

  sims_client: &sims_client
    build:
      context: .
      dockerfile: ./compose/local/sims_client/Dockerfile
    image: local_sims_client
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.backbone_server
      - ./.envs/.local/.postgres
      - ./.envs/.local/.sims_client
      - .env
    command: /start
    ports:
      - "4200:4200"

  nginx: &nginx
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    image: local_nginx
    ports:
      - "80:80"

  postgres:
    image: mdillon/postgis:10
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - ./compose/production/postgres/initdb:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    env_file:
      - ./.envs/.local/.postgres

  ldap:
    image: osixia/openldap:1.2.4
    env_file:
      - ./.envs/.local/.ldap
    volumes:
      - ldap_data_local:/var/lib/ldap
      - ldap_config_local:/etc/ldap/slap.d
      - ../malariagen-cas/util/ldap/bootstrap/custom:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: --copy-service --loglevel debug

networks:
  default:
    name: local_sims_backbone
