version: '2.4'

volumes:
  production-postgres-data: {}

services:
  production-backbone-server: &production-backbone-server
    build:
      context: .
      dockerfile: ./compose/production/backbone_server/Dockerfile
    image: production-backbone-server
    depends_on:
      - production-postgres
    env_file:
      - ./.envs/.production/.backbone_server
      - ./.envs/.production/.postgres
    ports:
      - "8100:8080"
    command: /start

  production-import: &production-import
    build:
      context: .
      dockerfile: ./compose/production/import/Dockerfile
    image: production-import
    depends_on:
      - production-postgres
    env_file:
      - ./.envs/.production/.backbone_server
      - ./.envs/.production/.postgres
    command: /start

  # Note that configuration properties need to be set in
  # ./client/sims-backbone/src/environments/environment.prod.ts
  # before building
  production-nginx: &production-nginx
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
      args:
        BUILD_AS: production
    image: production-nginx
    depends_on:
      - production-backbone-server
    ports:
      - "80:80"

  production-postgres:
    image: mdillon/postgis:10
    volumes:
      - production-postgres-data:/var/lib/postgresql/data
      - ./compose/production/postgres/initdb:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    env_file:
      - ./.envs/.production/.postgres

