# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: sims-event-set-service
#service: sims-backbone-service

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: "*"
  environment:
    POSTGRES_USER: ${file(../config.${self:provider.stage}.json):db_user}
    POSTGRES_DB: ${file(../config.${self:provider.stage}.json):database}
    POSTGRES_PASSWORD: ${file(../config.${self:provider.stage}.json):db_password}
    POSTGRES_PORT: ${file(../config.${self:provider.stage}.json):db_port}
    POSTGRES_HOST: ${cf:sims-backbone-service-${self:provider.stage}.DbHostOutput}
    AUTH_PROFILE_URL: ${file(../config.${self:provider.stage}.json):auth_profile}
    PYTHON_PATH: '.:../server:../server/bb_server'
  vpc:
    securityGroupIds:
      - ${cf:sims-backbone-service-${self:provider.stage}.ServerlessSecurityGroupOutput}
    subnetIds:
      - 'Fn::ImportValue': sims-backbone-service:PublicSubnetA-${self:provider.stage}
      - 'Fn::ImportValue': sims-backbone-service:PublicSubnetB-${self:provider.stage}
      - 'Fn::ImportValue': sims-backbone-service:PublicSubnetC-${self:provider.stage}
  apiGateway:
    restApiId: ${cf:sims-backbone-service-${self:provider.stage}.ApiGatewayRestApi}
    restApiRootResourceId: ${cf:sims-backbone-service-${self:provider.stage}.ApiGatewayRestApiRootResource}

plugins:
      - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

package:
    exclude:
        - requirements.txt
        - serverless.yml
        - node_modules/**
        - venv/**
        - package.json
        - package-lock.json
        - endpoints.txt
        - updateall.sh
        - ../../server/backbone_server/connect.py
    include:
        - ../util/**
        - event_set/handler.py
        - ../../server/bb_server/**
        - ../../server/backbone_server/**/**
        - ../client_secrets.${self:provider.stage}.json

functions:

  create_event_set:
    handler: event_set/handler.create_event_set
    events:
      - http:
          path: eventSet/{event_set_id}
          method: post
          cors: true
          timeout: 20
          authorizer:
            name: esAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                event_set_id: true
  download_event_set:
    handler: event_set/handler.download_event_set
    events:
      - http:
          path: eventSet/{event_set_id}
          method: get
          cors: true
          timeout: 20
          authorizer:
            name: esAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                event_set_id: true
  update_event_set:
    handler: event_set/handler.update_event_set
    events:
      - http:
          path: eventSet/{event_set_id}
          method: put
          cors: true
          timeout: 20
          authorizer:
            name: esAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                event_set_id: true
  delete_event_set:
    handler: event_set/handler.delete_event_set
    events:
      - http:
          path: eventSet/{event_set_id}
          method: delete
          cors: true
          timeout: 20
          authorizer:
            name: esAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                event_set_id: true

  create_event_set_item:
    handler: event_set/handler.create_event_set_item
    events:
      - http:
          path: eventSet/{event_set_id}/{sampling_event_id}
          method: post
          cors: true
          timeout: 20
          authorizer:
            name: esAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                event_set_id: true
                sampling_event_id: true
  delete_event_set_item:
    handler: event_set/handler.delete_event_set_item
    events:
      - http:
          path: eventSet/{event_set_id}/{sampling_event_id}
          method: delete
          cors: true
          timeout: 20
          authorizer:
            name: esAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                event_set_id: true
                sampling_event_id: true

  create_event_set_note:
    handler: event_set/handler.create_event_set_note
    events:
      - http:
          path: eventSet/{event_set_id}/notes/{note_id}
          method: post
          cors: true
          timeout: 20
          authorizer:
            name: esAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                event_set_id: true
                note_id: true
  update_event_set_note:
    handler: event_set/handler.update_event_set_note
    events:
      - http:
          path: eventSet/{event_set_id}/notes/{note_id}
          method: put
          cors: true
          timeout: 20
          authorizer:
            name: esAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                event_set_id: true
                note_id: true
  delete_event_set_note:
    handler: event_set/handler.delete_event_set_note
    events:
      - http:
          path: eventSet/{event_set_id}/notes/{note_id}
          method: delete
          cors: true
          timeout: 20
          authorizer:
            name: esAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                event_set_id: true
                note_id: true

  download_event_sets:
    handler: event_set/handler.download_event_sets
    events:
      - http:
          path: eventSets
          method: get
          cors: true
          timeout: 20
          authorizer:
            name: esAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*

resources:
  Resources:
    CreateUnderscoreeventUnderscoresetLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DownloadUnderscoreeventUnderscoresetLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    UpdateUnderscoreeventUnderscoresetLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DeleteUnderscoreeventUnderscoresetLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    CreateUnderscoreeventUnderscoresetUnderscoreitemLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DeleteUnderscoreeventUnderscoresetUnderscoreitemLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    CreateUnderscoreeventUnderscoresetUnderscorenoteLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    UpdateUnderscoreeventUnderscoresetUnderscorenoteLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DeleteUnderscoreeventUnderscoresetUnderscorenoteLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DownloadUnderscoreeventUnderscoresetsLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
