# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: sims-location-service
#service: sims-backbone-service

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: "*"
  environment:
    POSTGRES_USER: ${file(../config.${self:provider.stage}.json):db_user}
    POSTGRES_DB: ${file(../config.${self:provider.stage}.json):database}
    POSTGRES_PASSWORD: ${file(../config.${self:provider.stage}.json):db_password}
    POSTGRES_PORT: ${file(../config.${self:provider.stage}.json):db_port}
    POSTGRES_HOST: ${cf:sims-backbone-service-${self:provider.stage}.DbHostOutput}
    AUTH_PROFILE_URL: ${file(../config.${self:provider.stage}.json):auth_profile}
    PYTHON_PATH: '.:../server:../server/bb_server'
  vpc:
    securityGroupIds:
      - ${cf:sims-backbone-service-${self:provider.stage}.ServerlessSecurityGroupOutput}
    subnetIds:
      - 'Fn::ImportValue': sims-backbone-service:PublicSubnetA-${self:provider.stage}
      - 'Fn::ImportValue': sims-backbone-service:PublicSubnetB-${self:provider.stage}
      - 'Fn::ImportValue': sims-backbone-service:PublicSubnetC-${self:provider.stage}
  apiGateway:
    restApiId: ${cf:sims-backbone-service-${self:provider.stage}.ApiGatewayRestApi}
    restApiRootResourceId: ${cf:sims-backbone-service-${self:provider.stage}.ApiGatewayRestApiRootResource}

plugins:
      - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

package:
    exclude:
        - requirements.txt
        - serverless.yml
        - node_modules/**
        - venv/**
        - package.json
        - package-lock.json
        - endpoints.txt
        - updateall.sh
        - ../../server/backbone_server/connect.py
    include:
        - ../util/**
        - location/handler.py
        - ../../server/bb_server/**
        - ../../server/backbone_server/**/**
        - ../client_secrets.${self:provider.stage}.json

functions:

  create_location:
    handler: location/handler.create_location
    events:
      - http:
          path: location
          method: post
          cors: true
          timeout: 20
          authorizer:
            name: lsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*

  download_location:
    handler: location/handler.download_location
    events:
      - http:
          path: location/{location_id}
          method: get
          cors: true
          timeout: 20
          authorizer:
            name: lsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                location_id: true
  update_location:
    handler: location/handler.update_location
    events:
      - http:
          path: location/{location_id}
          method: put
          cors: true
          timeout: 20
          authorizer:
            name: lsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                location_id: true
  delete_location:
    handler: location/handler.delete_location
    events:
      - http:
          path: location/{location_id}
          method: delete
          cors: true
          timeout: 20
          authorizer:
            name: lsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                location_id: true

  download_gps_location:
    handler: location/handler.download_gps_location
    events:
      - http:
          path: location/gps/{latitude}/{longitude}
          method: get
          cors: true
          timeout: 20
          authorizer:
            name: lsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                latitude: true
                longitude: true

  download_partner_location:
    handler: location/handler.download_partner_location
    events:
      - http:
          path: location/partner/{partner_id}
          method: get
          cors: true
          timeout: 20
          authorizer:
            name: lsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                partner_id: true

  download_locations:
    handler: location/handler.download_locations
    events:
      - http:
          path: locations
          method: get
          cors: true
          timeout: 300
          authorizer:
            name: lsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              query:
                study_name: false
                start: false
                count: false
                orderby: false

resources:
  Resources:
    CreateUnderscorelocationLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DownloadUnderscorelocationLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    UpdateUnderscorelocationLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DeleteUnderscorelocationLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DownloadUnderscoregpsUnderscorelocationLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DownloadUnderscorepartnerUnderscorelocationLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DownloadUnderscorelocationsLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
