# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: sims-derivative-sample-service
#service: sims-backbone-service

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  timeout: 300
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: "*"
  environment:
    POSTGRES_USER: ${file(../config.${self:provider.stage}.json):db_user}
    POSTGRES_DB: ${file(../config.${self:provider.stage}.json):database}
    POSTGRES_PASSWORD: ${file(../config.${self:provider.stage}.json):db_password}
    POSTGRES_PORT: ${file(../config.${self:provider.stage}.json):db_port}
    POSTGRES_HOST: ${cf:sims-backbone-service-${self:provider.stage}.DbHostOutput}
    AUTH_PROFILE_URL: ${file(../config.${self:provider.stage}.json):auth_profile}
    PYTHON_PATH: '.:../server:../server/bb_server'
  vpc:
    securityGroupIds:
      - ${cf:sims-backbone-service-${self:provider.stage}.ServerlessSecurityGroupOutput}
    subnetIds:
      - 'Fn::ImportValue': sims-backbone-service:PublicSubnetA-${self:provider.stage}
      - 'Fn::ImportValue': sims-backbone-service:PublicSubnetB-${self:provider.stage}
      - 'Fn::ImportValue': sims-backbone-service:PublicSubnetC-${self:provider.stage}
  apiGateway:
    restApiId: ${cf:sims-backbone-service-${self:provider.stage}.ApiGatewayRestApi}
    restApiRootResourceId: ${cf:sims-backbone-service-${self:provider.stage}.ApiGatewayRestApiRootResource}

plugins:
      - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

package:
    exclude:
        - requirements.txt
        - serverless.yml
        - node_modules/**
        - venv/**
        - package.json
        - package-lock.json
        - endpoints.txt
        - updateall.sh
        - ../../server/backbone_server/connect.py
    include:
        - ../util/**
        - derivative_sample/handler.py
        - ../../server/bb_server/**
        - ../../server/backbone_server/**/**
        - ../client_secrets.${self:provider.stage}.json

functions:

  createDerivativeSample:
    handler: derivative_sample/handler.create_derivative_sample
    events:
      - http:
          path: derivativeSample
          method: post
          cors: true
          authorizer:
            name: dsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*

  downloadDerivativeSample:
    handler: derivative_sample/handler.download_derivative_sample
    events:
      - http:
          path: derivativeSample/{derivative_sample_id}
          method: get
          cors: true
          authorizer:
            name: dsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                derivative_sample_id: true

  downloadDerivativeSamples:
    handler: derivative_sample/handler.download_derivative_samples
    events:
      - http:
          path: derivativeSamples
          method: get
          cors: true
          authorizer:
            name: dsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              query:
                search_filter: false
                start: false
                count: false
                value_type: false

  downloadDsByStudy:
    handler: derivative_sample/handler.download_derivative_samples_by_study
    events:
      - http:
          path: derivativeSamples/study/{study_name}
          method: get
          cors: true
          authorizer:
            name: dsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                study_name: true
              query:
                start: false
                count: false

  downloadDsByEventSet:
    handler: derivative_sample/handler.download_derivative_samples_by_event_set
    events:
      - http:
          path: derivativeSamples/eventSet/{event_set_id}
          method: get
          cors: true
          authorizer:
            name: dsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                event_set_id: true
              query:
                start: false
                count: false

  updateDerivativeSample:
    handler: derivative_sample/handler.update_derivative_sample
    events:
      - http:
          path: derivativeSample/{derivative_sample_id}
          method: put
          cors: true
          authorizer:
            name: dsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                derivative_sample_id: true
  deleteDerivativeSample:
    handler: derivative_sample/handler.delete_derivative_sample
    events:
      - http:
          path: derivativeSample/{derivative_sample_id}
          method: delete
          cors: true
          authorizer:
            name: dsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                derivative_sample_id: true


  downloadDSByTaxa:
    handler: derivative_sample/handler.download_derivative_samples_by_taxa
    events:
      - http:
          path: derivativeSamples/taxa/{taxa_id}
          method: get
          cors: true
          authorizer:
            name: dsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                taxa_id: true
              query:
                search_filter: false
                start: false
                count: false

  downloadDSByAttr:
    handler: derivative_sample/handler.download_derivative_samples_by_attr
    events:
      - http:
          path: derivativeSamples/attr/{prop_name}/{prop_value}
          method: get
          cors: true
          authorizer:
            name: dsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                prop_name: true
                prop_value: true
              query:
                study_name: false
                start: false
                count: false
                value_type: false


  downloadDSByOsAttr:
    handler: derivative_sample/handler.download_derivative_samples_by_os_attr
    events:
      - http:
          path: derivativeSamples/os/attr/{prop_name}/{prop_value}
          method: get
          cors: true
          authorizer:
            name: dsAuthFunc
            arn: ${cf:sims-backbone-service-${self:provider.stage}.AuthFunc}
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
          request:
            parameters:
              paths:
                prop_name: true
                prop_value: true
              query:
                study_name: false
                start: false
                count: false
                value_type: false

resources:
  Resources:
    CreateDerivativeSampleLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DownloadDerivativeSampleLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DownloadDerivativeSamplesLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    UpdateDerivativeSampleLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DeleteDerivativeSampleLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DownloadDSByTaxaLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DownloadDSByAttrLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DownloadDSByOsAttrLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DownloadDsByStudyLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    DownloadDsByEventSetLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
