apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-import-secret-env
  name: {{ .Release.Name }}-import-secret-env
data:
  AWS_ACCESS_KEY_ID:  {{ .Values.import.id | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY:  {{ .Values.import.key | b64enc | quote }}
