apiVersion: v1
data:
  IMPORT_SOURCE: {{ .Values.import.source | quote }}
  IMPORT_DEST: {{ .Values.import.dest | quote }}
  ENVIRON: {{ .Values.import.environ | quote }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-import-env
  name: {{ .Release.Name }}-import-env
