apiVersion: v1
data:
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_HOST: {{ .Values.postgres.host | quote }}
  POSTGRES_PORT: "5432"
  POSTGRES_USER: {{ .Release.Name }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-postgres-env
  name: {{ .Release.Name }}-postgres-env
