apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-postgres-secret-env
  name: {{ .Release.Name }}-postgres-secret-env
data:
  POSTGRES_PASSWORD:  {{ .Values.postgres.password | b64enc | quote }}
