apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f production.yml -c
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-nginx-deployment
  name: {{ .Release.Name }}-nginx-deployment
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-nginx-deployment
    spec:
      containers:
      - name: {{ .Release.Name }}-nginx
        image: {{ .Values.image.registry }}{{ .Values.image.ngnix }}
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
